import { Geist, Geist_Mono } from "next/font/google";
import Footer from "./Component/Navbar/Footer";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "business website App",
  description: "Generated by business website app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className}  antialiased`}
      >
       
        {children}
        <Footer/>
      </body>
    </html>
  );
}
